spring:
  security:
    oauth2:
      client:
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/<tenant-id>/v2.0
            user-name-attribute: name
        registration:
          azure-dev:
            provider: azure
            client-id: <client-id>
            client-secret: <client-secret>
            scope:
              - openid
              - email
              - profile
